# Generated by Django 5.1.4 on 2025-01-30 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customuser_status_unreadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roll',
            field=models.CharField(choices=[('administration', 'Administration'), ('section', 'Section'), ('supervisor', 'Supervisor'), ('student', 'Student'), ('all', 'All')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='unreadmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_unread', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='unreadmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('deliver', 'Deliver')], default='unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='unreadmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhaseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forword', models.CharField(choices=[('administration', 'Administration'), ('section', 'Section'), ('supervisor', 'Supervisor'), ('student', 'Student'), ('all', 'All')], default='all', max_length=20)),
                ('fk_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_roll', to='chat.room')),
            ],
        ),
    ]
