# Generated by Django 5.1.4 on 2025-01-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_customuser_roll_alter_unreadmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasecontent',
            name='phase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
